[package]
name = "blob_share"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
clap = { version = "4.4.8", features = ["derive"] }
env_logger = "0.10.1"
ethers = "2.0.11"
eyre = "0.6.9"
hex = "0.4.3"
log = "0.4.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.34.0", features = ["macros", "rt"] }

[dev-dependencies]
reqwest = "0.11.22"

