[workspace]
members = [
    "bundler",
    "bundler_client",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
reqwest = "0.11.22"

bundler_client = { path = "bundler_client" }

